### PR TITLE
Decamove support

### PR DESCRIPTION
**Pull request by ballfn**
Support for decamove hardware and the mobile app via the [official sdk](https://github.com/MegadodoGames/DecaMoveSDK)
Works on both SteamVR and oculus

Current features include in game calibration with a toggleable button or one click on the decamove itself

### CODE REVIEW

**Comment by Erimelowo** [comment]
Please remove the “decamove edition” branding.
Apart from that, looks good. I’ll test it whenever I have time!

**Comment by ballfn** [comment]
Oh god I missed that 😅

**Comment by Erimelowo** [comment]
what is 
```
        public static void DecaButtonText()
        {
            return;
            int batt = (int) deca.battery;
            if (deca != null && _decaLastBattery != batt)
            {
                string battMsg = deca.battery >= 0 ? $"\n🔋:{deca.battery}%" : "";
                if (decaButton != null) decaButton.Text = $"Calibrate Deca{battMsg}";
                _decaLastBattery = batt;
            }
        }
```

for? Is it code that didn't work? Can I just remove it (I assume so; it's not used anywhere)?

_BetterLocomotion.cs line 213_

**Comment by Erimelowo** [comment]
Damnit I don't have an Android to test Decamove ._.

Everything works fine on my side (with Vive trackers). I pushed some formatting changes; please test with decamove to make sure it still works fine :3 

Also, I removed that battery display(?) code. You add another commit if you want to make what you were trying to do with it work, but it didn't do anything and was unreachable code in its current state.

**Comment by ballfn** [comment]
Tested it and it works fine, and yeah the battery thing was planned but I scrap it

Also, one slight concern thing there is I sometimes got crashes and some GC error, I don't know the cause of it yet nor can I reproduce it repeatedly yet

**Comment by Erimelowo** [comment]
Oh yeah just got an error in the console.
```

[22:25:57.461] [BetterLocomotion] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object
  at BetterLocomotion.Main.FindAssignedBone (UnityEngine.Transform trackerTransform) [0x00020] in <f87ccf89faf44b648720e55ccee482bc>:0
  at BetterLocomotion.Main.GetTracker (UnityEngine.HumanBodyBones bodyPart) [0x0001f] in <f87ccf89faf44b648720e55ccee482bc>:0
  at BetterLocomotion.Main.OnUpdate () [0x0000b] in <f87ccf89faf44b648720e55ccee482bc>:0
  at MelonLoader.MelonHandler+<>c.<OnUpdate>b__50_0 (MelonLoader.MelonBase x) [0x00000] in <0f6d2009dc5d4313a30db0346f3f685b>:0
  at MelonLoader.MelonHandler+<>c__DisplayClass54_0.<InvokeMelonMethod>b__1 (MelonLoader.MelonMod x) [0x00000] in <0f6d2009dc5d4313a30db0346f3f685b>:0
  at MelonLoader.MelonHandler.InvokeMelonMethod[T] (System.Collections.Generic.List`1[T]& melons, MelonLoader.MelonHandler+InvokeMelonMethodDelegate`1[T] method, System.Boolean remove_failed) [0x00032] in <0f6d2009dc5d4313a30db0346f3f685b>:0
```

**Comment by Erimelowo** [comment]
Alright, hopefully, I fixed that error.

Can you check what exception you got? Your console logs should be around `C:\Program Files (x86)\Steam\steamapps\common\VRChat\MelonLoader\Logs`

**Comment by ballfn** [comment]
On the crashes there was no exception in the log and the GC error is a popup which I suspect might be related to the sdk (unfortunately forgot to take a screenshot of it)

**Comment by Erimelowo** [comment]
The crashes might just be VRChat being VRChat tbh. I don’t see anything you’ve done that could crash the game, except if the SDK is the problem.

I’ll keep using this version for a couple of days and look out for errors or unusual crashing and merge it if I don’t have any problem like this weekend.

Take a screenshot of that popup next time if you get it again :p

**Comment by ballfn** [comment]
image
Got the error I mentioned `note to self: stop taking screenshot with VD`

> Fatal error in GC
> Collecting from unknown thread

There weren't any useful logs apart from some warning from the sdk a few minutes earlier before the crash
```
[10:28:28.825] [BetterLocomotion] [DecaSDK] Feedback: 7
[10:28:28.849] [BetterLocomotion] [DecaSDK] Unknown Move.Feedback, blame deca.
[10:28:30.826] [BetterLocomotion] [DecaSDK] DecaLog: "[2022-05-14 10:28:30.824] [DecaSDK] [warning] Unprocessed packet: 34 - [74] [74] [00] [01] [00] [00] [00] [00] [76] [76] [01] [02] [03] [00] [ff] [01] [03] [02] [02] [ff] [02] [cb] [1a] [0c] [fe] [ad] [e9] [02] [67] [94] [1d] [0f] [7e] [c2]

" logLevel: Warn
[10:28:31.831] [BetterLocomotion] [DecaSDK] State: Open
[10:28:32.827] [BetterLocomotion] [DecaSDK] State: Paired
[10:28:33.117] [BetterLocomotion] [DecaSDK] State: Streaming
```

**Comment by Erimelowo** [comment]
Does this crash the game or is it just an error?  

Are you sure this does’t happen at all without mods or with the normal version of BetterLocomotion?

I didn’t get this error after 10-ish hours, so I’m gonna assume this is because of the SDK. 

Did you modify its code? If you did, please check to see what you could have broken.  If you didn’t, could you report it on their Discord to see if they happen to know something about it (they linked it somewhere in the sdk…)?


Something I would like to do is to not touch the SDK at all for people that don’t have the locomotion mode set to deca. This would avoid errors and instability caused by the SDK **just in case** (also maybe gain a tiny bit of performance). Currently you’re creating a DecamoveBehaviour on application start. Can you move it to On settings change/save? Better for you to do it since you can actually test with your decamove and make sure it works!
*(don’t forget to add checks for “if (deca != null)” in other parts of the code like when you’re assigning the head transform!)*
In pseudocode:
```
// Called whenever the settings get saved/change.
if (locomotionmode == locomotionmode.deca){
    If (deca == null){
      deca = new decabehaviour{
      logger = logger
      }
    }
}

**Comment by ballfn** [comment]
It did crashes the game and I have only encountered this error with this version. I did modify some part of the sdk but not the part of the dll (also it is impossible to get into contact with anyone on deca since they are practically dead lol)

Also yeah I was thinking about adding that too and maybe properly destroy and unload it when they change mode too.

**Comment by ballfn** [comment]
I wanted to unload the sdk after switching to another loco mode but the sdk keep crashing so right now it will load once after deca is selected and stay loaded until game restarts with another loco mode selected (as a bonus the dll also won't drop into the plugins folder until deca is selected for the first time)

**Comment by Erimelowo** [comment]
That sounds good. _Guess Deca’s SDK is pretty bad lol._
~~I left some formatting comments on Github about missed spaces, please check them out…~~ Nevermind that I forgot I can just fix it from Github’s web thingy…

I’ll test that version this evening, thanks!!

**Comment by oestradiol** [comment]
Don't worry too much about the GC error.
That's most likely not something that's being caused by this mod, as it is known to happen nevertheless. It does happen without this mod, too.
Guess u were just lucky not to see it happening on your side, lmao.
I myself have experienced that error multiple times before, and I've never ever used that SDK for anything hehe.

**Pull request merged**
